### ISSUE TITLE
Zorka apparently conflicts with WAR class loader policy

### ISSUE THREAD

**Issue by B5r1oJ0A9G** [jitlogic/zorka#145] opened 2014-08-25 12:42 UTC
Hi!

We're giving Zorka agent a try regarding monitoring of application servers via Zabbix.

Now some applications stopped working after deploying Zorka agent. It turned out that the reason for that is somehow connected to having 'Single class loader for application' selected in 'WAR class loader policy'.

Since the AS in question can't be configured to use a 'Class loader for each WAR file in application' (dunno why, it's a statement from the developers), I wonder if this is something that can be "fixed' or worked-around in Zorka agent.

This is a log message I got from an application administrator encountering this issue:

```
WebContainer  E com.ibm.ws.webcontainer.internal.WebContainer handleRequest SRVE0255E: A WebGroup/Virtual Host to handle ***.jsp has not been defined.
```

Another possibly important information is that the application itself completely stopped logging when Zorka was deployed.

I recall a similar issues when using Zorka agent on some of our JBoss applications servers. Can't give any details yet since the respective admin is currently on vacation.

Environment:
- Zorka agent 1.0.6
- Websphere Application Server 8.5.5.2
- IBM JDK 1.7 (com.ibm.websphere.IBMJAVA.v70_7.0.6001.20140324_2202)
- Zabbix 2.2

**Comment by jitlogic** [comment] 2017-12-08 16:58
I've fixed a nasty bug regarding JDK7/8 and stack maps calculation some time ago. It was causing spurious class loads from time to time that were bypassing instrumentation (and possibly violating custom class loader policies). It was appearing in various contexts especially with JDK8, I suppose it was the cause of this issue. I'm closing this, if you still have problems please reopen.

**Closed** 2017-12-08 16:59 UTC
